Intern Task Rita Bunets: Task homework4
ritabunets/AutomationLab pull request #3
Opened 2022-10-31 10:17 UTC by ritabunets

2022-10-31 16:15 UTC, yauhenists requested changes

2022-10-31 20:40 UTC, ritabunets commented on Homework4/Program.cs
> +                Console.WriteLine("Labas!");
fixed

2022-10-31 20:41 UTC, ritabunets commented on Homework4/Program.cs
> +            sum = numbers[0] + numbers[4];
fixed

2022-10-31 20:41 UTC, ritabunets commented on Homework4/Program.cs
> +            int maxNumber = numbers.ToList().IndexOf(numbers.Max());
fixed

2022-11-01 08:04 UTC, yauhenists requested changes

2022-11-01 08:04 UTC, yauhenists commented on Homework4/Program.cs
> +            string condWord = "Hello";
Not a mistake - usually such variables can be declared as constants

2022-11-01 08:04 UTC, yauhenists commented on Homework4/Program.cs
> +                {
Here is the problem - you don't remember new max and min values when condition is met:
e.g. you have {3, 5, 4, 1, 2} - you will get indexMax = 2, indexMin = 4

2022-11-01 10:08 UTC, ritabunets commented on Homework4/Program.cs
> +                {
Not sure I understand you correctly. 
1) Based on you example {3, 5, 4, 1, 2} - I will get indexMax =1, indexMin = 3. Am I right?
2) Why do I need to save max or min values? The task is related to their indexes. I do not need to save the value, I need to know its index. Is it correct?

2022-11-01 10:08 UTC, ritabunets commented on Homework4/Program.cs
> +            string condWord = "Hello";
fixed

2022-11-01 14:56 UTC, yauhenists approved these changes

2022-11-01 15:27 UTC, merged